export enum Constants {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  STUDENT = 'STUDENT',
  NONSTUDENT = 'NON-STUDENT',
  BOTH = 'BOTH',
  BOGO = 'BOGO',
  DISCOUNTED = 'DISCOUNTED',
  ADMIN = 'ADMIN',
  MERCHANT = 'MERCHANT',
  USER = 'USER',
  FEED = 'FEED',
  REVIEW = 'REVIEW',
}
